# Generated by Django 3.1.5 on 2021-04-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='İsim')),
                ('keywords', models.CharField(max_length=255, verbose_name='Anahtar Kelimeler')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Resim')),
                ('status', models.CharField(choices=[('False', 'Yanlış'), ('True', 'Doğru')], max_length=5, verbose_name='Durum')),
                ('slug', models.SlugField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='İsim')),
                ('keywords', models.CharField(max_length=255, verbose_name='Anahtar Kelimeler')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Resim')),
                ('detail', models.TextField(verbose_name='detaylar')),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('slug', models.SlugField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
