# Generated by Django 3.1.5 on 2021-04-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('smtpserver', models.CharField(max_length=255)),
                ('smtpemail', models.CharField(max_length=255)),
                ('smtppassword', models.CharField(max_length=255)),
                ('smtpport', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('aboutus', models.TextField()),
                ('referenced', models.TextField()),
                ('status', models.CharField(choices=[('False', 'Yanlış'), ('True', 'Doğru')], max_length=10)),
                ('create_at', models.CharField(max_length=255)),
                ('upload_at', models.CharField(max_length=255)),
            ],
        ),
    ]
