# Generated by Django 3.1.5 on 2021-04-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_setting_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='upload_at',
        ),
        migrations.AddField(
            model_name='setting',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
