# Generated by Django 3.1.5 on 2021-04-30 20:09

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210430_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='referenced',
        ),
        migrations.AddField(
            model_name='setting',
            name='references',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
